entities:
  lg_ensol_ochang_factory: "an international factory deployment in South Korea"
  lg_sinarmas_technology_solutions: "a Fortune 500 industrial conglomerate in Southeast Asia"
  pt_polychemie_asia_pacific_permai: "a chemical manufacturing plant in Indonesia"
  university_of_indonesia: "a university physics research lab"
